In [8]:


data <- read.csv("datas/mmse_kadai1.csv", header=FALSE,col.names = c("x1","x2","y"))
x <- as.matrix(data[,c("x1","x2")])
y <- as.matrix(data[,"y"])

regression_simple <- function(x, y){

    theta_hat <- solve(t(x) %*% x) %*% t(x) %*% y
    sigma2_hat <- sum((y - x %*% theta_hat)^2) / (nrow(x) - ncol(x))
    err_cov_mat <- sigma2_hat * solve(t(x) %*% x)
    det_coef <- sum((mean(y) - x %*% theta_hat)^2) / sum((y - mean(y))^2)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}


exp1 <- function (x, y,n){
    x <- x[1:n,]
    y <- y[1:n,]
    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}
N_max <- nrow(x)
print (exp1(x, y, N_max)$theta_hat)
print (exp1(x, y, N_max)$err_cov_mat)
plot_exp1 <- function(x, y){
    ns <- c(2,4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    #ˆθN の各要素が収束していくことを片対数グラフでプロット,1つの図にまとめる
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in 1:length(ns)){
        n <- ns[i]
        result <- exp1(x, y, n)
        theta_hats[i, ] <- as.vector(result$theta_hat)  
    # matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat")
    png("graphs/task1.png")
    matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat")
    dev.off()
    }
}
plot_exp1(x, y)
print(exp1(x, y, N_max)$det_coef)

       [,1]
x1 1.506551
x2 1.997696
              x1            x2
x1  9.866491e-05 -4.081657e-07
x2 -4.081657e-07  1.005248e-04
[1] 0.8629734


In [9]:
data <- read.csv("datas/mmse_kadai2.csv", header=FALSE,col.names = c("x1","y"))
x0 <- rep(1, nrow(data))
x1 <- as.matrix(data[,c("x1")])
x2 <- x1^2
x3 <- x1^3
x <- cbind(x0, x1, x2, x3)
y <- as.matrix(data[,"y"])

exp2 <- function(x, y, n){
    # サンプルサイズ n に制限
    x <- x[1:n,]
    y <- y[1:n,]

    
    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}

plot_exp2 <- function(x, y){
    ns <- c(4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in 1:length(ns)){
        n <- ns[i]
        result <- exp2(x, y, n)
        theta_hats[i, ] <- as.vector(result$theta_hat)
    }
    png("graphs/task2.png")
    matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat (exp2)")
    dev.off()
}

N_max <- nrow(x)
print(exp2(x, y, N_max)$theta_hat)
print(exp2(x, y, N_max)$err_cov_mat)
print(exp2(x, y, N_max)$det_coef)
plot_exp2(x, y)

          [,1]
x0 -0.50902942
    1.97586067
    0.19774405
   -0.09866691
              x0                                          
x0  2.023442e-03 -1.186497e-05 -1.348312e-04  3.971165e-07
   -1.186497e-05  6.753015e-04 -1.898545e-07 -3.794719e-05
   -1.348312e-04 -1.898545e-07  1.603910e-05  6.351820e-08
    3.971165e-07 -3.794719e-05  6.351820e-08  2.528711e-06
[1] 0.461855


pdf 
  2

In [10]:
# ==== exp3: mmse_kadai3.csv 用 ====
# データ読込（x1, y）
data3 <- read.csv("datas/mmse_kadai3.csv", header = FALSE, col.names = c("x1","x2","y"))

# 特徴量設計: x1,x2,y
x <- as.matrix(data3[,c("x1","x2")])
y <- as.matrix(data3[,"y"])

# 回帰器（exp2と同一ロジック）
exp3 <- function(x, y, n){
    x <- x[1:n, , drop=FALSE]
    y <- y[1:n, , drop=FALSE]

    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef

    list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef)
}

# 収束プロット
plot_exp3 <- function(x, y){
    ns <- c(2,4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    ns <- ns[ns <= nrow(x)]  # データ数を超えないように制限
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp3(x, y, n)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task3.png")
    matplot(ns, theta_hats, type="b", log="x",
            xlab="n", ylab="theta_hat",
            main="Convergence of theta_hat (exp3)")
    dev.off()
}

# 実行例
N_max <- nrow(x)
print(exp3(x, y, N_max)$theta_hat)
print(exp3(x, y, N_max)$err_cov_mat)
print(exp3(x, y, N_max)$det_coef)
plot_exp3(x, y)


       [,1]
x1 2.373074
x2 1.537311
             x1           x2
x1  9.234588215 -0.003642121
x2 -0.003642121  9.264075136
[1] 0.0002841468


pdf 
  2

In [11]:
data <- read.csv("datas/mmse_kadai4.csv", header=FALSE, col.names = c("x1","y"))
x0 <- rep(1, nrow(data))
x1 <- as.matrix(data[,c("x1")])
x2 <- x1^2
x3 <- x1^3
x <- cbind(x0, x1, x2, x3)
y <- as.matrix(data[,"y"])

exp4 <- function(x, y, n){
    # サンプルサイズ n に制限
    x <- x[1:n, , drop=FALSE]
    y <- y[1:n, , drop=FALSE]
    result <- regression_simple(x, y)
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat,
        det_coef = result$det_coef
    )
}

# plot_exp4 <- function(x, y){
#     ns <- c(8,16,32,64,128,256,512,1024,2048,4096,8192)
#     ns <- ns[ns <= nrow(x)]  # データ数を超えないように制限
#     theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
#     for (i in 1:length(ns)){
#         n <- ns[i]
#         result <- exp4(x, y, n)
#         theta_hats[i, ] <- as.vector(result$theta_hat)
#     }
#     dir.create("graphs", showWarnings = FALSE)
#     png("graphs/task4.png")
#     matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat",
#             main="Convergence of theta_hat (exp4)")
#     dev.off()
# }

N_max <- nrow(x)
print(exp4(x, y, N_max)$theta_hat)
print(exp4(x, y, N_max)$err_cov_mat)
print(exp4(x, y, N_max)$det_coef)
# plot_exp4(x, y)

         [,1]
x0 -0.5777248
    2.0968228
   -0.3950467
    0.5491249
           x0                                 
x0  0.1532437  -1.148751   2.296352  -1.338869
   -1.1487510  11.458867 -25.752415  16.010391
    2.2963524 -25.752415  61.720073 -39.966014
   -1.3388695  16.010391 -39.966014  26.617392
[1] 0.04084128


In [41]:
regression_multiple <- function(x, y, V = NULL, Q = NULL){
    # x: m×1×nの3次元配列（m:特徴量数, 1:出力次元, n:サンプル数）
    # y: n×1行列（またはベクトル）
    if (is.null(ncol(y))) {
        y <- as.matrix(y, ncol = 1)
    }
    if (length(dim(x)) != 3) {
        stop("x must be a 3-dimensional array")
    }
    n <- dim(x)[3]
    m <- ncol(y)
    p <- dim(x)[1] # 特徴量数
    S <- matrix(0, p, p)
    b <- matrix(0, p, 1)
    T <- matrix(0, p, p)
    if (is.null(V)) {
        V <- diag(m)
    }
    if (is.null(Q)) {
        Q <- solve(V)
    }
    # m=1（スカラー出力）の場合はQ,Vをスカラー化
    if (m == 1) {
        Q <- as.numeric(Q)
        V <- as.numeric(V)
        for (i in 1:n) {
            xi <- as.matrix(x[,,i]) # (p,1)
            S <- S + xi %*% t(xi) * Q
            b <- b + xi * Q * y[i, 1]
            T <- T + xi %*% t(xi) * V
        }
    } else {
        for (i in 1:n) {
            xi <- as.matrix(x[,,i])
            yi <- matrix(y[i, ], nrow = m, ncol = 1)
            S <- S + t(xi) %*% Q %*% xi
            b <- b + t(xi) %*% Q %*% yi
            T <- T + t(xi) %*% V %*% xi
        }
    }
    theta_hat <- solve(S) %*% b
    err_cov_mat <- solve(S) %*% T %*% solve(S)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, S = S, b = b, T = T))
}

In [13]:
data <- read.csv("datas/mmse_kadai5.csv", header=FALSE, col.names = c("x12","y1","y2"))
x11 <- rep(1, nrow(data))
x12 <- as.matrix(data[,"x12"])
x21 <- rep(1, nrow(data))
x22 <- x12^2
m <- nrow(data)
x <- array(0, dim = c(2, 2, m))
for (i in 1:m) {
    x[,,i] <- matrix(c(x11[i], x12[i], x21[i], x22[i]), nrow = 2, byrow = TRUE)
}
y <- as.matrix(data[,c("y1","y2")])
N_max <- dim(x)[3]

exp5 <- function(x, y, n, method = "ols", V = matrix(c(100,0,0,1), 2, 2)){
    x <- x[,,1:n]
    y <- y[1:n, , drop=FALSE]
    
    if (method == "ols") {
        result <- regression_multiple(x, y)
    } else if (method == "wls") {
        result <- regression_multiple(x, y, V)
    }
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat
    )
}

plot_exp5 <- function(x, y, method = "ols", V = matrix(c(100,0,0,1), 2, 2)){
    ns <- c(4,8,16,32,64,128,256,512,1000)
    ns <- ns[ns <= dim(x)[3]]
    theta_hats <- matrix(0, nrow=length(ns), ncol=nrow(x[,,1]))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp5(x, y, n, method, V)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png(paste0("graphs/task5_", method, ".png"))
    matplot(ns, theta_hats, type="b", log="x",
            xlab="n", ylab="theta_hat",
            main=paste("Convergence of theta_hat (exp5 -", method, ")"))
    dev.off()
}
print ("OLS results:")
print(exp5(x, y, N_max, "ols")$theta_hat)
print(exp5(x, y, N_max, "ols")$err_cov_mat)
plot_exp5(x, y, "ols")
print ("WLS results:")
print(exp5(x, y, N_max, "wls")$theta_hat)
print(exp5(x, y, N_max, "wls")$err_cov_mat)
plot_exp5(x, y, "wls")

[1] "OLS results:"


          [,1]
[1,]  2.994567
[2,] -2.068971
              [,1]          [,2]
[1,]  0.0005762102 -0.0001504078
[2,] -0.0001504078  0.0002968433


pdf 
  2

[1] "WLS results:"
          [,1]
[1,]  2.939084
[2,] -1.986465
            [,1]        [,2]
[1,]  0.23999299 -0.09665406
[2,] -0.09665406  0.04991260


pdf 
  2

In [16]:
regression_multiple_different_distributions <- function(x, y, V1 = NULL,V2 = NULL, num = NULL){
    # x: m×m行列のn個の配列　
    # y: n×m行列
    if (is.null(V1)) {
        # 重みなしならm×mの単位行列
        V1 <- diag(m)
    }
    if (is.null(V2)) {
        # 重みなしならm×mの単位行列
        V2 <- diag(m)
    }
    n <- nrow(y)
    if (is.null(num) || num > n) {
        result <- regression_multiple(x, y, V1)
        return(result)
    }
    m <- ncol(y)

    Q1 <- solve(V1)
    Q2 <- solve(V2)
  
    S <- matrix(0,m,m)
    b <- matrix(0,m,1)
    T <- matrix(0,m,m)
    for (i in 1:num){
        
        xi <- x[,,i]
        yi <- matrix(c(y[i, ]), nrow=1)
        yi <- t(yi)

        S <- S + t(xi) %*% Q1 %*% xi
        b <- b + t(xi) %*% Q1 %*% yi
        T <- T + t(xi) %*% V1 %*% xi
    }
    for (i in (num+1):n){
        
        xi <- x[,,i]
        yi <- matrix(c(y[i, ]), nrow=1)
        yi <- t(yi)

        S <- S + t(xi) %*% Q2 %*% xi
        b <- b + t(xi) %*% Q2 %*% yi
        T <- T + t(xi) %*% V2 %*% xi
    }
    theta_hat <- solve(S) %*% b
    err_cov_mat <- solve(S) %*% T %*% solve(S)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat))
}


data <- read.csv("datas/mmse_kadai6.csv", header=FALSE, col.names = c("x12","y1","y2"))
x11 <- rep(1, nrow(data))
x12 <- as.matrix(data[,"x12"])
x21 <- rep(1, nrow(data))
x22 <- x12^2
m <- nrow(data)
x <- array(0, dim = c(2, 2, m))
for (i in 1:m) {
    x[,,i] <- matrix(c(x11[i], x12[i], x21[i], x22[i]), nrow = 2, byrow = TRUE)
}
y <- as.matrix(data[,c("y1","y2")])
N_max <- dim(x)[3]
V1 = matrix(c(100,0,0,1), 2, 2)
V2 = matrix(c(2,0,0,1), 2, 2)
# print (regression_multiple_different_distributions(x, y, V1 = matrix(c(100,0,0,1), 2, 2), V2 = matrix(c(2,0,0,1), 2, 2), num = 500)$theta_hat)

exp6 <- function(x, y, n, V1, V2, num , method = "ols"){
    x <- x[,,1:n]
    y <- y[1:n, , drop=FALSE]
    
    if (method == "ols") {
        result <- regression_multiple(x, y)
    } else if (method == "wls") {
        result <- regression_multiple_different_distributions(x, y, V1, V2, num)
    } 
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat
    )
}

plot_exp6 <- function(x, y, V1, V2, num , method = "wls"){
    ns <- seq(4, 1000, length.out = 20)
    ns <- ns[ns <= dim(x)[3]]
    theta_hats <- matrix(0, nrow=length(ns), ncol=nrow(x[,,1]))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp6(x, y, n, V1, V2, num , method)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png(paste0("graphs/task6_", method, ".png"))
    matplot(ns, theta_hats, type="b",
            xlab="n", ylab="theta_hat",
            main=paste("Convergence of theta_hat (exp6 -", method, ")"))
    dev.off()
}
print ("WLS results:")
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "wls")$theta_hat)
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "wls")$err_cov_mat)
plot_exp6(x, y, V1 = V1, V2 = V2, num = 500 , method = "wls")

print ("OLS results:")
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "ols")$theta_hat)
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "ols")$err_cov_mat)
plot_exp6(x, y, V1 = V1, V2 = V2, num = 500 , method = "ols")


[1] "WLS results:"
          [,1]
[1,]  2.994202
[2,] -2.014699
            [,1]        [,2]
[1,]  0.06019710 -0.02227335
[2,] -0.02227335  0.01276759


pdf 
  2

[1] "OLS results:"
          [,1]
[1,]  3.188356
[2,] -2.092183
              [,1]          [,2]
[1,]  0.0005692084 -0.0001402629
[2,] -0.0001402629  0.0002842674


pdf 
  2

In [45]:
data <- read.csv("datas/mmse_kadai7.csv", header=FALSE, col.names = c("x","y"))
# \[
# \begin{bmatrix}
# 1 & \exp\bigl(-\tfrac{(x_i - 1)^2}{2}\bigr) & \exp\bigl(-(x_i + 1)^2\bigr)
# \end{bmatrix}
# \]

x0 <- rep(1, nrow(data))
x1 <- exp(-(data$x - 1)^2 / 2)
x2 <- exp(-(data$x + 1)^2)
n <- nrow(data)
x <- array(0, dim = c(3, 1, n))
for (i in 1:n) {
    x[,,i] <- matrix(c(x0[i], x1[i], x2[i]), nrow = 3, ncol = 1)
}
y <- as.matrix(data[,"y"])
x_6000 <- x[, , 1:6000, drop=FALSE]
y_6000 <- y[1:6000, , drop=FALSE]
x_4000 <- x[, , 6001:10000, drop=FALSE]
y_4000 <- y[6001:10000, , drop=FALSE]

exp7 <- function(){
    S_6000 <- regression_multiple(x_6000, y_6000)$S
    S_4000 <- regression_multiple(x_4000, y_4000)$S
    theta_6000 <- regression_multiple(x_6000, y_6000)$theta_hat
    theta_4000 <- regression_multiple(x_4000, y_4000)$theta_hat
    print ("S6000:")
    print (S_6000)
    print ("S4000:")
    print (S_4000)
    print ("theta6000:")
    print (theta_6000)
    print ("theta4000:")
    print (theta_4000)
    theta_6000_4000 <- solve(S_6000 + S_4000) %*% (S_6000 %*% theta_6000 + S_4000 %*% theta_4000)
    print ("theta6000_4000:")
    print (theta_6000_4000)
    print ("theta10000:")
    print (regression_multiple(x, y)$theta_hat)

}
exp7()

[1] "S6000:"
         [,1]     [,2]      [,3]
[1,] 6000.000 1505.370 1033.4989
[2,] 1505.370 1063.211  226.4010
[3,] 1033.499  226.401  720.5624
[1] "S4000:"
          [,1]     [,2]     [,3]
[1,] 4000.0000 971.1512 716.3177
[2,]  971.1512 679.4769 149.7493
[3,]  716.3177 149.7493 510.2238
[1] "theta6000:"
             [,1]
[1,] -0.003879385
[2,]  3.010714895
[3,] -1.989434350
[1] "theta4000:"
            [,1]
[1,] -0.02537589
[2,]  3.03489937
[3,] -1.97772731
[1] "theta6000_4000:"
           [,1]
[1,] -0.0124955
[2,]  3.0204300
[3,] -1.9848692
[1] "theta10000:"
           [,1]
[1,] -0.0124955
[2,]  3.0204300
[3,] -1.9848692
