In [59]:
regression_simple <- function(x, y){

    theta_hat <- solve(t(x) %*% x) %*% t(x) %*% y
    sigma2_hat <- sum((y - x %*% theta_hat)^2) / (nrow(x) - ncol(x))
    err_cov_mat <- sigma2_hat * solve(t(x) %*% x)
    det_coef <- sum((mean(y) - x %*% theta_hat)^2) / sum((y - mean(y))^2)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}


In [6]:


data <- read.csv("datas/mmse_kadai1.csv", header=FALSE,col.names = c("x1","x2","y"))
x <- as.matrix(data[,c("x1","x2")])
y <- as.matrix(data[,"y"])



exp1 <- function (x, y,n){
    x <- x[1:n,]
    y <- y[1:n,]
    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}
N_max <- nrow(x)
print (exp1(x, y, N_max)$theta_hat)
print (exp1(x, y, N_max)$err_cov_mat)
plot_exp1 <- function(x, y){
    ns <- c(2,4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    #ˆθN の各要素が収束していくことを片対数グラフでプロット,1つの図にまとめる
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in 1:length(ns)){
        n <- ns[i]
        result <- exp1(x, y, n)
        theta_hats[i, ] <- as.vector(result$theta_hat)  
    # matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat")
    png("graphs/task1.png")
    matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat")
    dev.off()
    }
}
plot_exp1(x, y)
print(exp1(x, y, N_max)$det_coef)

       [,1]
x1 1.506551
x2 1.997696
              x1            x2
x1  9.866491e-05 -4.081657e-07
x2 -4.081657e-07  1.005248e-04
              x1            x2
x1  9.866491e-05 -4.081657e-07
x2 -4.081657e-07  1.005248e-04
[1] 0.8629734
[1] 0.8629734


In [7]:
data <- read.csv("datas/mmse_kadai2.csv", header=FALSE,col.names = c("x1","y"))
x0 <- rep(1, nrow(data))
x1 <- as.matrix(data[,c("x1")])
x2 <- x1^2
x3 <- x1^3
x <- cbind(x0, x1, x2, x3)
y <- as.matrix(data[,"y"])

exp2 <- function(x, y, n){
    # サンプルサイズ n に制限
    x <- x[1:n,]
    y <- y[1:n,]

    
    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef))
}

plot_exp2 <- function(x, y){
    ns <- c(4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in 1:length(ns)){
        n <- ns[i]
        result <- exp2(x, y, n)
        theta_hats[i, ] <- as.vector(result$theta_hat)
    }
    png("graphs/task2.png")
    matplot(ns, theta_hats, type="b", log="x", xlab="n", ylab="theta_hat", main="Convergence of theta_hat (exp2)")
    dev.off()
}

N_max <- nrow(x)
print(exp2(x, y, N_max)$theta_hat)
print(exp2(x, y, N_max)$err_cov_mat)
print(exp2(x, y, N_max)$det_coef)
plot_exp2(x, y)

          [,1]
x0 -0.50902942
    1.97586067
    0.19774405
   -0.09866691
              x0                                          
x0  2.023442e-03 -1.186497e-05 -1.348312e-04  3.971165e-07
   -1.186497e-05  6.753015e-04 -1.898545e-07 -3.794719e-05
   -1.348312e-04 -1.898545e-07  1.603910e-05  6.351820e-08
    3.971165e-07 -3.794719e-05  6.351820e-08  2.528711e-06
[1] 0.461855
              x0                                          
x0  2.023442e-03 -1.186497e-05 -1.348312e-04  3.971165e-07
   -1.186497e-05  6.753015e-04 -1.898545e-07 -3.794719e-05
   -1.348312e-04 -1.898545e-07  1.603910e-05  6.351820e-08
    3.971165e-07 -3.794719e-05  6.351820e-08  2.528711e-06
[1] 0.461855


pdf 
  2

In [8]:
# ==== exp3: mmse_kadai3.csv 用 ====
# データ読込（x1, y）
data3 <- read.csv("datas/mmse_kadai3.csv", header = FALSE, col.names = c("x1","x2","y"))

# 特徴量設計: x1,x2,y
x <- as.matrix(data3[,c("x1","x2")])
y <- as.matrix(data3[,"y"])

# 回帰器（exp2と同一ロジック）
exp3 <- function(x, y, n){
    x <- x[1:n, , drop=FALSE]
    y <- y[1:n, , drop=FALSE]

    result <- regression_simple(x, y)
    theta_hat <- result$theta_hat
    err_cov_mat <- result$err_cov_mat    
    det_coef <- result$det_coef

    list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, det_coef = det_coef)
}

# 収束プロット
plot_exp3 <- function(x, y){
    ns <- c(2,4,8,16,32,64,128,256,512,1024,2048,4096,8192)
    ns <- ns[ns <= nrow(x)]  # データ数を超えないように制限
    theta_hats <- matrix(0, nrow=length(ns), ncol=ncol(x))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp3(x, y, n)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task3.png")
    matplot(ns, theta_hats, type="b", log="x",
            xlab="n", ylab="theta_hat",
            main="Convergence of theta_hat (exp3)")
    dev.off()
}

# 実行例
N_max <- nrow(x)
print(exp3(x, y, N_max)$theta_hat)
print(exp3(x, y, N_max)$err_cov_mat)
print(exp3(x, y, N_max)$det_coef)
plot_exp3(x, y)


       [,1]
x1 2.373074
x2 1.537311
             x1           x2
x1  9.234588215 -0.003642121
x2 -0.003642121  9.264075136
             x1           x2
x1  9.234588215 -0.003642121
x2 -0.003642121  9.264075136
[1] 0.0002841468
[1] 0.0002841468


pdf 
  2

In [ ]:
data <- read.csv("datas/mmse_kadai4.csv", header=FALSE, col.names = c("x1","y"))
x0 <- rep(1, nrow(data))
x1 <- as.matrix(data[,c("x1")])
x2 <- x1^2
x3 <- x1^3
x <- cbind(x0, x1, x2, x3)
y <- as.matrix(data[,"y"])

exp4 <- function(x, y, n){
    # サンプルサイズ n に制限
    x <- x[1:n, , drop=FALSE]
    y <- y[1:n, , drop=FALSE]
    result <- regression_simple(x, y)
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat,
        det_coef = result$det_coef
    )
}

N_max <- nrow(x)
print(exp4(x, y, N_max)$theta_hat)
print(exp4(x, y, N_max)$err_cov_mat)
print(exp4(x, y, N_max)$det_coef)
# plot_exp4(x, y)

         [,1]
x0 -0.5777248
    2.0968228
   -0.3950467
    0.5491249
           x0                                 
x0  0.1532437  -1.148751   2.296352  -1.338869
   -1.1487510  11.458867 -25.752415  16.010391
    2.2963524 -25.752415  61.720073 -39.966014
   -1.3388695  16.010391 -39.966014  26.617392
[1] 0.04084128
           x0                                 
x0  0.1532437  -1.148751   2.296352  -1.338869
   -1.1487510  11.458867 -25.752415  16.010391
    2.2963524 -25.752415  61.720073 -39.966014
   -1.3388695  16.010391 -39.966014  26.617392
[1] 0.04084128


In [10]:
regression_multiple <- function(x, y, V = NULL, Q = NULL){
    # y: n×1行列（またはベクトル）
    if (is.null(ncol(y))) {
        y <- as.matrix(y, ncol = 1)
    }
    if (length(dim(x)) != 3) {
        stop("x must be a 3-dimensional array")
    }
    n <- dim(x)[3]
    m <- ncol(y)
    p <- dim(x)[1] # 特徴量数
    S <- matrix(0, p, p)
    b <- matrix(0, p, 1)
    T <- matrix(0, p, p)
    if (is.null(V)) {
        V <- diag(m)
    }
    if (is.null(Q)) {
        Q <- solve(V)
    }
    # m=1（スカラー出力）の場合はQ,Vをスカラー化
    if (m == 1) {
        Q <- as.numeric(Q)
        V <- as.numeric(V)
        for (i in 1:n) {
            xi <- as.matrix(x[,,i]) # (p,1)
            S <- S + xi %*% t(xi) * Q
            b <- b + xi * Q * y[i, 1]
            T <- T + xi %*% t(xi) * V
        }
    } else {
        for (i in 1:n) {
            xi <- as.matrix(x[,,i])
            yi <- matrix(y[i, ], nrow = m, ncol = 1)
            S <- S + t(xi) %*% Q %*% xi
            b <- b + t(xi) %*% Q %*% yi
            T <- T + t(xi) %*% V %*% xi
        }
    }
    theta_hat <- solve(S) %*% b
    err_cov_mat <- solve(S) %*% T %*% solve(S)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat, S = S, b = b, T = T))
}

In [11]:
data <- read.csv("datas/mmse_kadai5.csv", header=FALSE, col.names = c("x12","y1","y2"))
x11 <- rep(1, nrow(data))
x12 <- as.matrix(data[,"x12"])
x21 <- rep(1, nrow(data))
x22 <- x12^2
m <- nrow(data)
x <- array(0, dim = c(2, 2, m))
for (i in 1:m) {
    x[,,i] <- matrix(c(x11[i], x12[i], x21[i], x22[i]), nrow = 2, byrow = TRUE)
}
y <- as.matrix(data[,c("y1","y2")])
N_max <- dim(x)[3]

exp5 <- function(x, y, n, method = "ols", V = matrix(c(100,0,0,1), 2, 2)){
    x <- x[,,1:n]
    y <- y[1:n, , drop=FALSE]
    
    if (method == "ols") {
        result <- regression_multiple(x, y)
    } else if (method == "wls") {
        result <- regression_multiple(x, y, V)
    }
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat
    )
}

plot_exp5 <- function(x, y, method = "ols", V = matrix(c(100,0,0,1), 2, 2)){
    ns <- c(4,8,16,32,64,128,256,512,1000)
    ns <- ns[ns <= dim(x)[3]]
    theta_hats <- matrix(0, nrow=length(ns), ncol=nrow(x[,,1]))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp5(x, y, n, method, V)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png(paste0("graphs/task5_", method, ".png"))
    matplot(ns, theta_hats, type="b", log="x",
            xlab="n", ylab="theta_hat",
            main=paste("Convergence of theta_hat (exp5 -", method, ")"))
    dev.off()
}
print ("OLS results:")
print(exp5(x, y, N_max, "ols")$theta_hat)
print(exp5(x, y, N_max, "ols")$err_cov_mat)
plot_exp5(x, y, "ols")
print ("WLS results:")
print(exp5(x, y, N_max, "wls")$theta_hat)
print(exp5(x, y, N_max, "wls")$err_cov_mat)
plot_exp5(x, y, "wls")

[1] "OLS results:"
          [,1]
[1,]  2.994567
[2,] -2.068971
          [,1]
[1,]  2.994567
[2,] -2.068971
              [,1]          [,2]
[1,]  0.0005762102 -0.0001504078
[2,] -0.0001504078  0.0002968433
              [,1]          [,2]
[1,]  0.0005762102 -0.0001504078
[2,] -0.0001504078  0.0002968433


pdf 
  2

[1] "WLS results:"
          [,1]
[1,]  2.939084
[2,] -1.986465
          [,1]
[1,]  2.939084
[2,] -1.986465
            [,1]        [,2]
[1,]  0.23999299 -0.09665406
[2,] -0.09665406  0.04991260
            [,1]        [,2]
[1,]  0.23999299 -0.09665406
[2,] -0.09665406  0.04991260


pdf 
  2

In [ ]:
regression_multiple_different_distributions <- function(x, y, V1 = NULL,V2 = NULL, num = NULL){
    # x: m×m行列のn個の配列　
    # y: n×m行列
    if (is.null(V1)) {
        # 重みなしならm×mの単位行列
        V1 <- diag(m)
    }
    if (is.null(V2)) {
        # 重みなしならm×mの単位行列
        V2 <- diag(m)
    }
    n <- nrow(y)
    if (is.null(num) || num > n) {
        result <- regression_multiple(x, y, V1)
        return(result)
    }
    m <- ncol(y)

    Q1 <- solve(V1)
    Q2 <- solve(V2)
  
    S <- matrix(0,m,m)
    b <- matrix(0,m,1)
    T <- matrix(0,m,m)
    for (i in 1:num){
        
        xi <- x[,,i]
        yi <- matrix(c(y[i, ]), nrow=1)
        yi <- t(yi)

        S <- S + t(xi) %*% Q1 %*% xi
        b <- b + t(xi) %*% Q1 %*% yi
        T <- T + t(xi) %*% V1 %*% xi
    }
    for (i in (num+1):n){
        
        xi <- x[,,i]
        yi <- matrix(c(y[i, ]), nrow=1)
        yi <- t(yi)

        S <- S + t(xi) %*% Q2 %*% xi
        b <- b + t(xi) %*% Q2 %*% yi
        T <- T + t(xi) %*% V2 %*% xi
    }
    theta_hat <- solve(S) %*% b
    err_cov_mat <- solve(S) %*% T %*% solve(S)
    return(list(theta_hat = theta_hat, err_cov_mat = err_cov_mat))
}


data <- read.csv("datas/mmse_kadai6.csv", header=FALSE, col.names = c("x12","y1","y2"))
x11 <- rep(1, nrow(data))
x12 <- as.matrix(data[,"x12"])
x21 <- rep(1, nrow(data))
x22 <- x12^2
m <- nrow(data)
x <- array(0, dim = c(2, 2, m))
for (i in 1:m) {
    x[,,i] <- matrix(c(x11[i], x12[i], x21[i], x22[i]), nrow = 2, byrow = TRUE)
}
y <- as.matrix(data[,c("y1","y2")])
N_max <- dim(x)[3]
V1 = matrix(c(100,0,0,1), 2, 2)
V2 = matrix(c(2,0,0,1), 2, 2)
# print (regression_multiple_different_distributions(x, y, V1 = matrix(c(100,0,0,1), 2, 2), V2 = matrix(c(2,0,0,1), 2, 2), num = 500)$theta_hat)

exp6 <- function(x, y, n, V1, V2, num , method = "ols"){
    x <- x[,,1:n]
    y <- y[1:n, , drop=FALSE]
    
    if (method == "ols") {
        result <- regression_multiple(x, y)
    } else if (method == "wls") {
        result <- regression_multiple_different_distributions(x, y, V1, V2, num)
    } 
    list(
        theta_hat = result$theta_hat,
        err_cov_mat = result$err_cov_mat
    )
}

plot_exp6 <- function(x, y, V1, V2, num , method = "wls"){
    ns <- seq(4, 1000, length.out = 20)
    ns <- ns[ns <= dim(x)[3]]
    theta_hats <- matrix(0, nrow=length(ns), ncol=nrow(x[,,1]))
    for (i in seq_along(ns)){
        n <- ns[i]
        res <- exp6(x, y, n, V1, V2, num , method)
        theta_hats[i, ] <- as.vector(res$theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png(paste0("graphs/task6_", method, ".png"))
    matplot(ns, theta_hats, type="b",
            xlab="n", ylab="theta_hat",
            main=paste("Convergence of theta_hat (exp6 -", method, ")"))
    dev.off()
}

print ("OLS results:")
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "ols")$theta_hat)
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "ols")$err_cov_mat)
plot_exp6(x, y, V1 = V1, V2 = V2, num = 500 , method = "ols")

print ("WLS results:")
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "wls")$theta_hat)
print(exp6(x, y, N_max, V1 = V1, V2 = V2, num = 500 , method = "wls")$err_cov_mat)
plot_exp6(x, y, V1 = V1, V2 = V2, num = 500 , method = "wls")




[1] "WLS results:"
          [,1]
[1,]  2.994202
[2,] -2.014699
          [,1]
[1,]  2.994202
[2,] -2.014699
            [,1]        [,2]
[1,]  0.06019710 -0.02227335
[2,] -0.02227335  0.01276759
            [,1]        [,2]
[1,]  0.06019710 -0.02227335
[2,] -0.02227335  0.01276759


pdf 
  2

[1] "OLS results:"
          [,1]
[1,]  3.188356
[2,] -2.092183
          [,1]
[1,]  3.188356
[2,] -2.092183
              [,1]          [,2]
[1,]  0.0005692084 -0.0001402629
[2,] -0.0001402629  0.0002842674
              [,1]          [,2]
[1,]  0.0005692084 -0.0001402629
[2,] -0.0001402629  0.0002842674


pdf 
  2

In [13]:
data <- read.csv("datas/mmse_kadai7.csv", header=FALSE, col.names = c("x","y"))
# \[
# \begin{bmatrix}
# 1 & \exp\bigl(-\tfrac{(x_i - 1)^2}{2}\bigr) & \exp\bigl(-(x_i + 1)^2\bigr)
# \end{bmatrix}
# \]

x0 <- rep(1, nrow(data))
x1 <- exp(-(data$x - 1)^2 / 2)
x2 <- exp(-(data$x + 1)^2)
n <- nrow(data)
x <- array(0, dim = c(3, 1, n))
for (i in 1:n) {
    x[,,i] <- matrix(c(x0[i], x1[i], x2[i]), nrow = 3, ncol = 1)
}
y <- as.matrix(data[,"y"])
x_6000 <- x[, , 1:6000, drop=FALSE]
y_6000 <- y[1:6000, , drop=FALSE]
x_4000 <- x[, , 6001:10000, drop=FALSE]
y_4000 <- y[6001:10000, , drop=FALSE]

exp7 <- function(){
    S_6000 <- regression_multiple(x_6000, y_6000)$S
    S_4000 <- regression_multiple(x_4000, y_4000)$S
    theta_6000 <- regression_multiple(x_6000, y_6000)$theta_hat
    theta_4000 <- regression_multiple(x_4000, y_4000)$theta_hat
    print ("S6000:")
    print (S_6000)
    print ("S4000:")
    print (S_4000)
    print ("theta6000:")
    print (theta_6000)
    print ("theta4000:")
    print (theta_4000)
    theta_6000_4000 <- solve(S_6000 + S_4000) %*% (S_6000 %*% theta_6000 + S_4000 %*% theta_4000)
    print ("theta6000_4000:")
    print (theta_6000_4000)
    print ("theta10000:")
    print (regression_multiple(x, y)$theta_hat)

}
exp7()

[1] "S6000:"
         [,1]     [,2]      [,3]
[1,] 6000.000 1505.370 1033.4989
[2,] 1505.370 1063.211  226.4010
[3,] 1033.499  226.401  720.5624
[1] "S4000:"
          [,1]     [,2]     [,3]
[1,] 4000.0000 971.1512 716.3177
[2,]  971.1512 679.4769 149.7493
[3,]  716.3177 149.7493 510.2238
[1] "theta6000:"
             [,1]
[1,] -0.003879385
[2,]  3.010714895
[3,] -1.989434350
[1] "theta4000:"
            [,1]
[1,] -0.02537589
[2,]  3.03489937
[3,] -1.97772731
[1] "theta6000_4000:"
           [,1]
[1,] -0.0124955
[2,]  3.0204300
[3,] -1.9848692
[1] "theta10000:"
           [,1]
[1,] -0.0124955
[2,]  3.0204300
[3,] -1.9848692


In [14]:
data <- read.csv("datas/mmse_kadai7.csv", header=FALSE, col.names = c("x","y"))
# \[
# \begin{bmatrix}
# 1 & \exp\bigl(-\tfrac{(x_i - 1)^2}{2}\bigr) & \exp\bigl(-(x_i + 1)^2\bigr)
# \end{bmatrix}
# \]

x0 <- rep(1, nrow(data))
x1 <- exp(-(data$x - 1)^2 / 2)
x2 <- exp(-(data$x + 1)^2)
n <- nrow(data)
x <- array(0, dim = c(3, 1, n))
for (i in 1:n) {
    x[,,i] <- matrix(c(x0[i], x1[i], x2[i]), nrow = 3, ncol = 1)
}
y <- as.matrix(data[,"y"])
x_mat <- t(matrix(x, nrow = 3, ncol = n))
x_6000 <- x[, , 1:6000, drop=FALSE]
x_6000_mat <- t(matrix(x_6000, nrow = 3, ncol = 6000))
y_6000 <- y[1:6000, , drop=FALSE]
x_4000 <- x[, , 6001:10000, drop=FALSE]
x_4000_mat <- t(matrix(x_4000, nrow = 3, ncol = 4000))
y_4000 <- y[6001:10000, , drop=FALSE]
exp8 <- function(){
    theta_hat_full <- regression_multiple(x, y)$theta_hat
    theta_hat_6000 <- regression_multiple(x_6000, y_6000)$theta_hat
    theta_hat_4000 <- regression_multiple(x_4000, y_4000)$theta_hat
    V_hat_full <- sum((y - x_mat %*% theta_hat_full)^2) / (nrow(x_mat) - ncol(x_mat))
    V_hat_6000 <- sum((y_6000 - x_6000_mat %*% theta_hat_6000)^2) / (nrow(x_6000_mat) - ncol(x_6000_mat))
    V_hat_4000 <- sum((y_4000 - x_4000_mat %*% theta_hat_4000)^2) / (nrow(x_4000_mat) - ncol(x_4000_mat))
    S_6000 <- regression_multiple(x_6000, y_6000,V = V_hat_6000)$S
    S_4000 <- regression_multiple(x_4000, y_4000,V = V_hat_4000)$S
    theta_6000 <- regression_multiple(x_6000, y_6000,V = V_hat_6000)$theta_hat
    theta_4000 <- regression_multiple(x_4000, y_4000,V = V_hat_4000)$theta_hat
    print ("theta_6000:")
    print (theta_6000)
    print ("theta_4000:")
    print (theta_4000)
    theta_6000_4000 <- solve(S_6000 + S_4000) %*% (S_6000 %*% theta_6000 + S_4000 %*% theta_4000)
    print ("theta6000_4000:")
    print (theta_6000_4000)
    print ("theta10000:")
    print (regression_multiple(x, y,V = V_hat_full)$theta_hat)
}
exp8()

[1] "theta_6000:"
             [,1]
[1,] -0.003879385
[2,]  3.010714895
[3,] -1.989434350
[1] "theta_4000:"
            [,1]
[1,] -0.02537589
[2,]  3.03489937
[3,] -1.97772731
[1] "theta6000_4000:"
            [,1]
[1,] -0.01245376
[2,]  3.02038299
[3,] -1.98489169
[1] "theta10000:"
           [,1]
[1,] -0.0124955
[2,]  3.0204300
[3,] -1.9848692


In [2]:
update_regression_mat <- function(Phi_N, phi_N_plus_1,theta_N,y_N_plus_1,gamma=1){
    
    I_m <- diag(1)  # 単位行列
    
    # 式: Phi_{N+1} = Phi_N - Phi_N * phi_{N+1} * (I_m + phi_{N+1}^T * Phi_N * phi_{N+1})^{-1} * phi_{N+1}^T * Phi_N
    
    # 中間計算
    phi_T_Phi_phi <- phi_N_plus_1 %*% Phi_N %*% t(phi_N_plus_1)  # スカラーまたは (1 x 1)
    
    # 逆行列の項
    inv_term <- solve( (gamma * I_m) + phi_T_Phi_phi )  #  スカラー

    K <- gamma * (Phi_N %*% t(phi_N_plus_1) %*% inv_term)
    # 更新
    Phi_N_plus_1 <- (Phi_N - K %*% phi_N_plus_1 %*% Phi_N ) / gamma
    theta_N_plus_1 <- theta_N + K %*% (y_N_plus_1 - phi_N_plus_1 %*% theta_N)
    return(list(Phi_N_plus_1 = Phi_N_plus_1, theta_N_plus_1 = theta_N_plus_1))
    
}

In [3]:


w <- function(){
    runif(1, min = -1, max = 1)
}

update_tick <- function(y_k_1, y_k_2, F_k_2, M = 2, D = 1, K = 3, delta_t = 0.01){
    y_k <- (2 - (D / M) * delta_t) * y_k_1 -
           (1 - (D / M) * delta_t + (K / M) * delta_t^2) * y_k_2 +
           (delta_t^2 / M) * F_k_2 +
           w()
    return(y_k)
}

exp9_1 <- function(){
    # Fは常に0
    y_k <- 0
    y_k_1 <- 0
    y_k_2 <- 0
    F_k_2 <- 1
    Phi <- diag(3) *1000
    theta_hat <- matrix(c(0,0,0), nrow = 3, ncol = 1)
    y <- c()
    x <- array(0, dim = c(3, 1, 10000))
    for (i in 1:10000) {
        y_k_2 <- y_k_1
        y_k_1 <- y_k
        y_k <- update_tick(y_k_1, y_k_2, F_k_2)
        y <- rbind(y, y_k)
        yk <- matrix(c(y_k), nrow = 1, ncol = 1)
        xi <- matrix(c(y_k_1, y_k_2, F_k_2), nrow = 1, ncol = 3)
        x[,,i] <- xi
        update <- update_regression_mat(Phi, xi, theta_hat, y_k)
        Phi <- update$Phi_N_plus_1
        theta_hat <- update$theta_N_plus_1

    }
    # result <- regression_multiple(x, y)

    print ("exp9_1 theta estimate ")
    print(theta_hat)
}

exp9_2 <- function(){
    # Fはsin波
    y_k <- 0
    y_k_1 <- 0
    y_k_2 <- 0
    Phi <- diag(3) *1000
    theta_hat <- matrix(c(0,0,0), nrow = 3, ncol = 1)
    y <- c()
    x <- array(0, dim = c(3, 1, 10000))
    for (i in 1:10000) {
        F_k_2 <- sin(pi * i / 5)
        y_k_2 <- y_k_1
        y_k_1 <- y_k
        y_k <- update_tick(y_k_1, y_k_2, F_k_2)
        y <- rbind(y, y_k)
        yk <- matrix(c(y_k), nrow = 1, ncol = 1)
        xi <- matrix(c(y_k_1, y_k_2, F_k_2), nrow = 1, ncol = 3)
        x[,,i] <- xi
        update <- update_regression_mat(Phi, xi, theta_hat, y_k)
        Phi <- update$Phi_N_plus_1
        theta_hat <- update$theta_N_plus_1
    }
    print ("exp9_2 theta estimate ")
    print(theta_hat)
}

exp9_3 <- function(){
    
    y_k <- 0
    y_k_1 <- 0
    y_k_2 <- 0
    Phi <- diag(3) *1000
    theta_hat <- matrix(c(0,0,0), nrow = 3, ncol = 1)
    y <- c()
    x <- array(0, dim = c(3, 1, 10000))
    for (i in 1:10000) {
        F_k_2 <- 10000*sin(pi * i / 5)
        y_k_2 <- y_k_1
        y_k_1 <- y_k
        y_k <- update_tick(y_k_1, y_k_2, F_k_2)
        y <- rbind(y, y_k)
        yk <- matrix(c(y_k), nrow = 1, ncol = 1)
        xi <- matrix(c(y_k_1, y_k_2, F_k_2), nrow = 1, ncol = 3)
        x[,,i] <- xi
        update <- update_regression_mat(Phi, xi, theta_hat, y_k)
        Phi <- update$Phi_N_plus_1
        theta_hat <- update$theta_N_plus_1
    }
    print ("exp9_3 theta estimate ")
    print(theta_hat)
}

exp9_1()
exp9_2()
exp9_3()

[1] "exp9_1 theta estimate "
            [,1]
[1,]  1.99515410
[2,] -0.99532391
[3,]  0.00215087
[1] "exp9_2 theta estimate "
             [,1]
[1,]  1.995721237
[2,] -0.995895110
[3,]  0.002637203
[1] "exp9_3 theta estimate "
              [,1]
[1,]  1.994996e+00
[2,] -9.951249e-01
[3,]  4.883587e-05


In [58]:



exp10 <- function(){
    y_k <- 0
    Phi <- matrix(1000, nrow = 1, ncol = 1)
    theta_hat <- matrix(c(0), nrow = 1, ncol = 1)
    y <- c()
    theta_hats <- c()
    for (k in 1:10000) {
        w_k <- sample(c(-1, 1), 1)
        y_k <- sin(0.0001 * k) + w_k
        y <- rbind(y, y_k)
        yk <- matrix(c(y_k), nrow = 1, ncol = 1)
        xi <- matrix(c(1), nrow = 1, ncol = 1)
        update <- update_regression_mat(Phi, xi, theta_hat, y_k, gamma = 0.99)
        Phi <- update$Phi_N_plus_1
        theta_hat <- update$theta_N_plus_1
        theta_hats <- rbind(theta_hats, theta_hat)
    }
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task10.png")
    plot(1:10000, theta_hats, type="l", col="blue", ylim=c(-1.5, 1.5),
         xlab="k", ylab="theta_hat", main="Estimation of non-stationary time series (exp10)")
    lines(1:10000, sin(0.0001 * (1:10000)), col="red")
    legend("topright", legend=c("Estimated theta_hat", "True theta"), col=c("blue", "red"), lty=1)
    dev.off()
}
exp10()

pdf 
  2

In [ ]:
update_kalman_filter <- function(theta_k_1, V_k_1, y_k, a_k, c_k, sigma2_v, sigma2_w) {
    
    # (3.37) X_k = a_k^2 * V_{k-1} + σ_v^2
    X_k <- a_k^2 * V_k_1 + sigma2_v
    
    # (3.39) F_k = (c_k * X_k) / (c_k^2 * X_k + σ_w^2)
    F_k <- (c_k * X_k) / (c_k^2 * X_k + sigma2_w)
    
    # (3.36) θ_k = a_k * θ_{k-1} + F_k * (y_k - c_k * a_k * θ_{k-1})
    theta_k <- a_k * theta_k_1 + F_k * (y_k - c_k * a_k * theta_k_1)
    
    # (3.38) V_k = (σ_w^2 * X_k) / (c_k^2 * X_k + σ_w^2)
    V_k <- (sigma2_w * X_k) / (c_k^2 * X_k + sigma2_w)
    
    return(list(
        theta_k = theta_k,
        V_k = V_k,
        X_k = X_k,
        F_k = F_k
    ))
}

In [19]:
# データ生成関数（exp11とexp12で共通使用）
generate_kalman_data <- function(seed = 123, N = 100, a_k = 0.9, c_k = 2, sigma2_v = 1, sigma2_w = 1) {
    # 乱数シードを設定
    set.seed(seed)
    
    # 初期値
    theta_0 <- rnorm(1, mean = 3, sd = sqrt(2))  # θ_0 ~ N(3, 2)
    V_0 <- 2
    
    # データ格納用
    theta_true <- numeric(N)
    y_obs <- numeric(N)
    
    # 初期化
    theta_k_1 <- theta_0
    
    # データ生成
    for (k in 1:N) {
        # 真の状態遷移 (3.40): θ_k = a_k * θ_{k-1} + v_k
        v_k <- rnorm(1, mean = 0, sd = sqrt(sigma2_v))
        theta_k <- a_k * theta_k_1 + v_k
        theta_true[k] <- theta_k
        
        # 観測 (3.41): y_k = c_k * θ_k + w_k
        w_k <- rnorm(1, mean = 0, sd = sqrt(sigma2_w))
        y_k <- c_k * theta_k + w_k
        y_obs[k] <- y_k
        
        # 次のステップへ
        theta_k_1 <- theta_k
    }
    
    # データを返す
    return(list(
        theta_true = theta_true,
        y_obs = y_obs,
        theta_0 = theta_0,
        V_0 = V_0,
        a_k = a_k,
        c_k = c_k,
        sigma2_v = sigma2_v,
        sigma2_w = sigma2_w,
        N = N
    ))
}

# カルマンフィルタの実行（フォワードパスのみ）
exp11 <- function(data) {
    # パラメータ取得
    theta_true <- data$theta_true
    y_obs <- data$y_obs
    theta_0 <- data$theta_0
    V_0 <- data$V_0
    a_k <- data$a_k
    c_k <- data$c_k
    sigma2_v <- data$sigma2_v
    sigma2_w <- data$sigma2_w
    N <- data$N
    
    # 推定値格納用
    theta_hat <- numeric(N)
    V_all <- numeric(N)
    
    # 初期化
    theta_k_1 <- theta_0
    V_k_1 <- V_0
    
    # Kalmanフィルタによる推定（フォワードパス）
    for (k in 1:N) {
        kalman_result <- update_kalman_filter(theta_k_1, V_k_1, y_obs[k], a_k, c_k, sigma2_v, sigma2_w)
        theta_hat[k] <- kalman_result$theta_k
        V_all[k] <- kalman_result$V_k
        V_k_1 <- kalman_result$V_k
        theta_k_1 <- kalman_result$theta_k
    }
    
    # プロット
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task11.png")
    plot(1:N, theta_true, type="l", col="red", lwd=2,
         xlab="k", ylab="theta", main="Kalman Filter Estimation (exp11)",
         ylim=range(c(theta_true, theta_hat)))
    lines(1:N, theta_hat, col="blue", lwd=2)
    legend("topright", legend=c("True theta_k", "Filtered theta_hat_k"), 
           col=c("red", "blue"), lty=1, lwd=2)
    dev.off()
    
    # 結果の一部を表示
    cat("exp11: Kalman Filter (Forward Pass Only)\n")
    cat("mmse:", mean((theta_true - theta_hat)^2), "\n")

    
    # 結果を返す
    return(list(
        theta_hat = theta_hat,
        V_all = V_all
    ))
}

In [20]:
update_kalman_smoother <- function(theta_k, theta_k_plus_1_s, V_k, V_k_plus_1_s, X_k_plus_1, a_k) {
    # theta_k: フィルタリングで得られた θ_k (フォワードパスの結果)
    # theta_k_plus_1_s: スムージングで得られた θ^s_{k+1} (バックワードパスの結果)
    # V_k: フィルタリングで得られた V_k
    # V_k_plus_1_s: スムージングで得られた V^s_{k+1}
    # X_k_plus_1: 予測誤差共分散 X_{k+1} = a_k^2 * V_k + σ_v^2
    # a_k: システムパラメータ a_k
    
    # (3.43) g_k = a_k * V_k / X_{k+1}
    g_k <- a_k * V_k / X_k_plus_1
    
    # (3.42) θ^s_k = θ_k + g_k * (θ^s_{k+1} - a_k * θ_k)
    theta_k_s <- theta_k + g_k * (theta_k_plus_1_s - a_k * theta_k)
    
    # (3.44) V^s_k = V_k + g_k^2 * (V^s_{k+1} - X_{k+1})
    V_k_s <- V_k + g_k^2 * (V_k_plus_1_s - X_k_plus_1)
    
    return(list(
        theta_k_s = theta_k_s,
        V_k_s = V_k_s,
        g_k = g_k
    ))
}

In [21]:
# カルマンスムーザーの実行（フォワード + バックワードパス）
exp12 <- function(data) {
    # パラメータ取得
    theta_true <- data$theta_true
    y_obs <- data$y_obs
    theta_0 <- data$theta_0
    V_0 <- data$V_0
    a_k <- data$a_k
    c_k <- data$c_k
    sigma2_v <- data$sigma2_v
    sigma2_w <- data$sigma2_w
    N <- data$N
    
    # 推定値格納用
    theta_hat <- numeric(N)
    V_all <- numeric(N)
    X_all <- numeric(N)
    
    # 初期化
    theta_k_1 <- theta_0
    V_k_1 <- V_0
    
    # === フォワードパス: Kalmanフィルタによる推定 ===
    for (k in 1:N) {
        kalman_result <- update_kalman_filter(theta_k_1, V_k_1, y_obs[k], a_k, c_k, sigma2_v, sigma2_w)
        theta_hat[k] <- kalman_result$theta_k
        V_all[k] <- kalman_result$V_k
        X_all[k] <- kalman_result$X_k
        V_k_1 <- kalman_result$V_k
        theta_k_1 <- kalman_result$theta_k
    }
    
    # === バックワードパス: Kalmanスムーザーによる修正 ===
    theta_smooth <- numeric(N)
    V_smooth <- numeric(N)
    
    # 終端条件: θ^s_N = θ_N, V^s_N = V_N
    theta_smooth[N] <- theta_hat[N]
    V_smooth[N] <- V_all[N]
    
    # 逆方向に処理
    for (k in (N-1):1) {
        smoother_result <- update_kalman_smoother(
            theta_hat[k],           # フィルタリング結果 θ_k
            theta_smooth[k + 1],    # スムージング結果 θ^s_{k+1}
            V_all[k],               # フィルタリング誤差共分散 V_k
            V_smooth[k + 1],        # スムージング誤差共分散 V^s_{k+1}
            X_all[k + 1],           # 予測誤差共分散 X_{k+1}
            a_k
        )
        theta_smooth[k] <- smoother_result$theta_k_s
        V_smooth[k] <- smoother_result$V_k_s
    }
    
    # プロット: 真値、フィルタリング結果、スムージング結果を比較
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task12.png")
    plot(1:N, theta_true, type="l", col="red", lwd=2,
         xlab="k", ylab="theta", main="Kalman Smoother Estimation (exp12)",
         ylim=range(c(theta_true, theta_hat, theta_smooth)))
    lines(1:N, theta_smooth, col="green", lwd=2)
    legend("topright", 
           legend=c("True theta_k", "Smoothed theta^s_k"), 
           col=c("red", "green"), lty=c(1, 1), lwd=2)
    dev.off()
    
    # 結果の一部を表示
    cat("\nexp12: Kalman Smoother (Forward + Backward Pass)\n")
    cat("mmse:", mean((theta_true - theta_smooth)^2), "\n")
    
    # 結果を返す
    return(list(
        theta_hat = theta_hat,
        theta_smooth = theta_smooth,
        V_all = V_all,
        V_smooth = V_smooth
    ))
}

In [28]:
# 同じデータを使ってexp11とexp12を実行
# データ生成（乱数シード固定で再現性を確保）
kalman_data <- generate_kalman_data(seed = 42, N = 100, a_k = 0.9, c_k = 2, sigma2_v = 1, sigma2_w = 1)

# exp11: カルマンフィルタ（フォワードパスのみ）
result11 <- exp11(kalman_data)

# exp12: カルマンスムーザー（フォワード + バックワードパス）
result12 <- exp12(kalman_data)

exp11: Kalman Filter (Forward Pass Only)
mmse: 0.1935684 

exp12: Kalman Smoother (Forward + Backward Pass)
mmse: 0.1716128 

exp12: Kalman Smoother (Forward + Backward Pass)
mmse: 0.1716128 


In [ ]:
data <- read.csv("datas/mmse_kadai13.csv", header=FALSE, col.names = c("x","y"))
x0 <- rep(1, nrow(data))
x1 <- as.matrix(data[,"x"])
x2 <- x1^2
x3 <- x1^3
y <- as.matrix(data[,"y"])
n <- nrow(data)
x <- array(0, dim = c(2, 3, n))
for (i in 1:n) {
    x[,,i] <- matrix(c(x0[i], x1[i],x1[i],x2[i],x2[i], x3[i]), nrow = 2, ncol = 3)
}


x_T <- array(0, dim = c(3,2,n))
for (i in 1:n) {
    x_T[,,i] <- t(x[,,i])
}
N_max <- dim(x)[3]


for ( z in 1:10){
    alpha <- matrix(runif(2), nrow = 2)
    beta <- matrix(runif(3), nrow = 3)
    
    # alphaの軌跡とdiffを記録
    alpha_trajectory <- matrix(0, nrow = 1000, ncol = 2)
    alpha_trajectory[1, ] <- alpha
    diff_history <- numeric(1000)
    
    diff <- Inf
    for (z2 in 1:1000) {
        x_alpha <- matrix(0, nrow = n, ncol = 3)
        for (i in 1:n) {
            x_alpha[i, ] <- t(alpha) %*% x[, , i]
        }
        result <- regression_simple(x_alpha, y)
        beta_new <- result$theta_hat
        
        x_beta <- matrix(0, nrow = n, ncol = 2)
        for (i in 1:n) {
            x_beta[i,  ] <- t(beta_new) %*% x_T[, , i]
        }
        result2 <- regression_simple(x_beta, y)
        alpha_new <- result2$theta_hat
        
        # alphaの軌跡を保存
        if (z2 < 1000) {
            alpha_trajectory[z2 + 1, ] <- alpha_new
        }
        
        # diffを計算して保存
        diff <- max(sqrt(sum((alpha_new - alpha)^2)), sqrt(sum((beta_new - beta)^2)))
        diff_history[z2] <- diff
        
        if (diff < 1e-6) {
            print ("Converged:")
            print (sum(y - x_beta %*% alpha_new)^2)
            print ("alpha*betaT")
            print (alpha_new %*% t(beta_new))
            alpha_trajectory <- alpha_trajectory[1:(z2+1), ]
            diff_history <- diff_history[1:z2]
            break
        }
        alpha <- alpha_new
        beta <- beta_new

    }
    
    print(paste("Final diff:", diff))
    
    # alphaの軌跡をプロット
    dir.create("graphs", showWarnings = FALSE)
    png("graphs/task13_trajectory.png", width = 800, height = 600)
    plot(alpha_trajectory[, 1], alpha_trajectory[, 2], type="b", pch=16, cex=0.5,
         xlab="alpha_1", ylab="alpha_2", main="Alpha trajectory (exp13)", col="blue")
    # 初期値を強調
    points(alpha_trajectory[1, 1], alpha_trajectory[1, 2], pch=16, cex=2, col="green")
    # 最終値を強調
    points(alpha_trajectory[nrow(alpha_trajectory), 1], alpha_trajectory[nrow(alpha_trajectory), 2], 
           pch=16, cex=2, col="red")
    legend("topright", legend=c("Trajectory", "Initial", "Final"), 
           col=c("blue", "green", "red"), pch=16, pt.cex=c(0.5, 2, 2))
    dev.off()
    
    # diffの収束過程をプロット
    png("graphs/task13_convergence.png", width = 800, height = 600)
    plot(1:length(diff_history), diff_history, type="b", pch=16, cex=0.5, col="purple",
         xlab="Iteration", ylab="Max diff (alpha, beta)", 
         main="Convergence of parameters (exp13)", log="y")
    abline(h=1e-6, col="red", lty=2, lwd=2)
    legend("topright", legend=c("Max diff", "Threshold (1e-6)"), 
           col=c("purple", "red"), lty=c(1, 2), lwd=c(1, 2))
    dev.off()
}



[1] "Converged:"
[1] 2.962228e-08
[1] "alpha*betaT"
           [,1]      [,2]      [,3]
[1,]  0.5064504 -0.996694  2.000339
[2,] -1.0131692  1.993916 -4.001739
[1] "Final diff: 9.27252879369525e-07"
[1] "Converged:"
[1] 5.990368e-08
[1] "alpha*betaT"
           [,1]      [,2]      [,3]
[1,]  0.5064504 -0.996694  2.000339
[2,] -1.0131693  1.993916 -4.001739
[1] "Final diff: 8.34931461029014e-07"
[1] "Converged:"
[1] 4.206885e-08
[1] "alpha*betaT"
           [,1]       [,2]      [,3]
[1,]  0.5064505 -0.9966937  2.000341
[2,] -1.0131690  1.9939148 -4.001740
[1] "Final diff: 9.0615077585237e-07"
[1] "Converged:"
[1] 4.381157e-08
[1] "alpha*betaT"
           [,1]      [,2]      [,3]
[1,]  0.5064504 -0.996694  2.000339
[2,] -1.0131693  1.993916 -4.001739
[1] "Final diff: 8.67110877696347e-07"
[1] "Converged:"
[1] 1.671005e-07
[1] "alpha*betaT"
           [,1]       [,2]      [,3]
[1,]  0.5064505 -0.9966936  2.000341
[2,] -1.0131688  1.9939141 -4.001740
[1] "Final diff: 8.70911392101804e-07"


In [48]:
data <- read.csv("datas/mmse_kadai14.csv", header=FALSE, col.names = c("x1","x2"))

x <- as.matrix(data[,c("x1","x2")])

# K-meansクラスタリングの実装
k_means <- function(x, K, max_iters = 10000, tol = 1e-6) {
    n <- nrow(x)
    d <- ncol(x)
    
    # ランダムに初期クラスタ中心を選択
    centroids <- x[sample(1:n, K), ]
    
    cluster_assignments <- rep(0, n)
    for (iter in 1:max_iters) {
        # 各データポイントを最も近いクラスタ中心に割り当て
        for (i in 1:n) {
            distances <- apply(centroids, 1, function(centroid) sum((x[i, ] - centroid)^2))
            cluster_assignments[i] <- which.min(distances)
        }
        
        # 新しいクラスタ中心を計算
        new_centroids <- matrix(0, nrow = K, ncol = d)
        for (k in 1:K) {
            points_in_cluster <- x[cluster_assignments == k, , drop = FALSE]
            if (nrow(points_in_cluster) > 0) {
                new_centroids[k, ] <- colMeans(points_in_cluster)
            } else {
                new_centroids[k, ] <- centroids[k, ]  # クラスタにポイントがない場合は中心を維持
            }
        }
        
        # 収束判定
        if (max(sqrt(rowSums((new_centroids - centroids)^2))) < tol) {
            # 各データポイントから割り当てられた中心までの距離の合計を計算
            total_distance <- 0
            for (i in 1:n) {
                centroid_idx <- cluster_assignments[i]
                distance <- sum((x[i, ] - centroids[centroid_idx, ])^2)
                total_distance <- total_distance + distance
            }
            break
        }
        
        centroids <- new_centroids
    }
    
    return(list(
        centroids = centroids,
        cluster_assignments = cluster_assignments,
        total_distance = total_distance
    ))
}
K <- 3

# 複数のシードで試行して最小距離を見つける
best_distance <- Inf
best_seed <- NULL
best_result <- NULL

for (trial in 1:100){
    set.seed(trial)  
    kmeans_result <- k_means(x, K)
    cat(paste("Trial", trial, "Total distance:", kmeans_result$total_distance, "\n"))
    
    if (kmeans_result$total_distance < best_distance) {
        best_distance <- kmeans_result$total_distance
        best_seed <- trial
        best_result <- kmeans_result
    }
}

cat("\n=== Best Result ===\n")
cat(paste("Best seed:", best_seed, "\n"))
cat(paste("Minimum total distance:", best_distance, "\n"))
print ("Best K-means centroids:")
print (best_result$centroids)

# 最良の結果をプロット
dir.create("graphs", showWarnings = FALSE)
png("graphs/task14_kmeans.png", width = 800, height = 600)
plot(x, col = best_result$cluster_assignments, pch = 16,
     xlab = "x1", ylab = "x2", main = paste("K-means Clustering (exp14) - Best seed:", best_seed))
points(best_result$centroids, col = 1:K, pch = 8, cex = 2)
legend("topright", legend = paste("Cluster", 1:K), col = 1:K, pch = 16)
dev.off()


Trial 1 Total distance: 3516.14067351195 
Trial 2 Total distance: 4014.78794538446 
Trial 3 Total distance: 4014.78794538446 
Trial 4 Total distance: 4014.78794538446 
Trial 5 Total distance: 3516.14067351195 
Trial 6 Total distance: 4019.95093537037 
Trial 7 Total distance: 4014.78794538446 
Trial 8 Total distance: 3516.14067351195 
Trial 9 Total distance: 3516.14067351195 
Trial 10 Total distance: 4014.7864134626 
Trial 11 Total distance: 4014.78794538446 
Trial 12 Total distance: 3516.80093792281 
Trial 13 Total distance: 3516.80093792281 
Trial 14 Total distance: 4014.78794538446 
Trial 15 Total distance: 4014.78794538446 
Trial 16 Total distance: 3516.14067351195 
Trial 17 Total distance: 3516.14067351195 
Trial 18 Total distance: 4014.78794538446 
Trial 19 Total distance: 3516.14067351195 
Trial 20 Total distance: 4014.78794538446 
Trial 21 Total distance: 4014.78794538446 
Trial 22 Total distance: 4014.78794538446 
Trial 23 Total distance: 3516.14067351195 
Trial 24 Total distan

pdf 
  2

In [61]:
data <- read.csv("datas/mmse_kadai14.csv", header=FALSE, col.names = c("x1","x2"))

x <- as.matrix(data[,c("x1","x2")])

# K-meansクラスタリングの実装
k_means_re <- function(x, K, max_iters = 10000, tol = 1e-6) {
    n <- nrow(x)
    d <- ncol(x)
    
    # 指定した初期クラスタ中心を選択
    centroids <- matrix(c(-5, 0, 0, -2, 2, 0), nrow = K, ncol = d, byrow = TRUE)
    
    cluster_assignments <- rep(0, n)
    for (iter in 1:max_iters) {
        # 各データポイントを最も近いクラスタ中心に割り当て
        for (i in 1:n) {
            distances <- apply(centroids, 1, function(centroid) sum((x[i, ] - centroid)^2))
            cluster_assignments[i] <- which.min(distances)
        }
        
        # 新しいクラスタ中心を計算
        new_centroids <- matrix(0, nrow = K, ncol = d)
        for (k in 1:K) {
            points_in_cluster <- x[cluster_assignments == k, , drop = FALSE]
            if (nrow(points_in_cluster) > 0) {
                new_centroids[k, ] <- colMeans(points_in_cluster)
            } else {
                new_centroids[k, ] <- centroids[k, ]  # クラスタにポイントがない場合は中心を維持
            }
        }
        
        # 収束判定
        if (max(sqrt(rowSums((new_centroids - centroids)^2))) < tol) {
            # 各データポイントから割り当てられた中心までの距離の合計を計算
            total_distance <- 0
            for (i in 1:n) {
                centroid_idx <- cluster_assignments[i]
                distance <- sum((x[i, ] - centroids[centroid_idx, ])^2)
                total_distance <- total_distance + distance
            }
            break
        }
        
        centroids <- new_centroids
    }
    
    return(list(
        centroids = centroids,
        cluster_assignments = cluster_assignments,
        total_distance = total_distance
    ))
}
K <- 3

# 指定した初期中心でK-meansを実行
result <- k_means_re(x, K)

cat("\n=== Result with Specified Initial Centers ===\n")
cat(paste("Total distance:", result$total_distance, "\n"))
print("K-means centroids:")
print(result$centroids)

# 結果をプロット
dir.create("graphs", showWarnings = FALSE)
png("graphs/task14_kmeans_re.png", width = 800, height = 600)
plot(x, col = result$cluster_assignments, pch = 16,
     xlab = "x1", ylab = "x2", main = "K-means Clustering (exp14_re)")
points(result$centroids, col = 1:K, pch = 8, cex = 2)
legend("topright", legend = paste("Cluster", 1:K), col = 1:K, pch = 16)
dev.off()



=== Result with Specified Initial Centers ===
Total distance: 3516.14067351195 
[1] "K-means centroids:"
Total distance: 3516.14067351195 
[1] "K-means centroids:"
            [,1]       [,2]
[1,] -5.03743972  0.3097801
[2,] -0.02043697 -1.1683454
[3,]  3.51182562 -0.8325374
            [,1]       [,2]
[1,] -5.03743972  0.3097801
[2,] -0.02043697 -1.1683454
[3,]  3.51182562 -0.8325374


pdf 
  2